# Data parameters
data:
  seed: 777
  data_path: '~/.pytorch/CITYSCAPES_data/'
  batch_size: 256
  shuffle: True
  drop_last: True
  download: True
  num_workers: 4
  img_size: [224, 224]

# Model parameters
model:
  num_class: 35
  num_block: 8
  dim_channel: 128
  mul_factor: 2
  dropout: 0.5

# Training parameters
train:
  epochs: 100
  lr: 0.001
  betas: [0.9, 0.999]
  eps: 0.00000001
  weight_decay: 0.01

# Save
save:
  model_name: 'cityscapes'

# Other parameters
others:
  log_period: 100