# Data parameters
data:
  seed: 777
  train_data_path: '~/.pytorch/PLACES365_data/train'
  val_data_path: '~/.pytorch/PLACES365_data/val'
  batch_size: 128
  shuffle: True
  drop_last: True
  download: True
  num_workers: 4
  img_size: [64, 64]

# Model parameters
model:
  num_class: 365
  num_block: 7
  dim_channel: 128
  mul_factor: 2
  dropout: 0.5

# Training parameters
train:
  epochs: 100
  lr: 0.001
  betas: [0.9, 0.999]
  eps: 0.00000001
  weight_decay: 0.01

# Save
save:
  model_name: 'places365'

# Other parameters
others:
  log_period: 50